name: SonarQube

on: push

jobs:
  sonarqube:
    name: SonarQube Scan
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Scan
      uses: kitabisa/sonarqube-action@v1.1.0
      with:
        projectKey: "fom-api"
        host: ${{ secrets.SONARQUBE_HOST }}
        login: ${{ secrets.SONARQUBE_TOKEN }}
